# Exclude problematic URLs and patterns
exclude_path = [
    ".git",
    "target",
    "venv",
    "__pycache__",
]
exclude = [
    # Ignore all localhost ips
    "regex:^http://localhost(:\d+)?/",
    
    # Internal IP
    "regex:^http://147.45.234.218(:\d+)?/",

    # Private GitLab
    "https://gitlab.pg.innopolis.university/",
    
    # GitHub settings pages (require login)
    "https://github.com/mrZom49/Traffic-Proccessor-SWP-46/settings/rules/",
    "https://github.com/SWP-Team-46/Traffic-Proccessor/settings/rules/",
]

# Increase timeout
timeout = 30
